// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: int128.proto

#include "int128.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace storage_util {
PROTOBUF_CONSTEXPR Int128::Int128(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.high_)*/int64_t{0}
  , /*decltype(_impl_.low_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Int128DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Int128DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Int128DefaultTypeInternal() {}
  union {
    Int128 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Int128DefaultTypeInternal _Int128_default_instance_;
}  // namespace storage_util
static ::_pb::Metadata file_level_metadata_int128_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_int128_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_int128_2eproto = nullptr;

const uint32_t TableStruct_int128_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::storage_util::Int128, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::storage_util::Int128, _impl_.high_),
  PROTOBUF_FIELD_OFFSET(::storage_util::Int128, _impl_.low_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::storage_util::Int128)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::storage_util::_Int128_default_instance_._instance,
};

const char descriptor_table_protodef_int128_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014int128.proto\022\014storage_util\"+\n\006Int128\022\020"
  "\n\004high\030\001 \001(\003B\0020\001\022\017\n\003low\030\002 \001(\004B\0020\001B\033\n\027com"
  ".google.storage.utilP\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_int128_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_int128_2eproto = {
    false, false, 110, descriptor_table_protodef_int128_2eproto,
    "int128.proto",
    &descriptor_table_int128_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_int128_2eproto::offsets,
    file_level_metadata_int128_2eproto, file_level_enum_descriptors_int128_2eproto,
    file_level_service_descriptors_int128_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_int128_2eproto_getter() {
  return &descriptor_table_int128_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_int128_2eproto(&descriptor_table_int128_2eproto);
namespace storage_util {

// ===================================================================

class Int128::_Internal {
 public:
};

Int128::Int128(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:storage_util.Int128)
}
Int128::Int128(const Int128& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Int128* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){}
    , decltype(_impl_.low_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.high_, &from._impl_.high_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.low_) -
    reinterpret_cast<char*>(&_impl_.high_)) + sizeof(_impl_.low_));
  // @@protoc_insertion_point(copy_constructor:storage_util.Int128)
}

inline void Int128::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){int64_t{0}}
    , decltype(_impl_.low_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Int128::~Int128() {
  // @@protoc_insertion_point(destructor:storage_util.Int128)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Int128::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Int128::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Int128::Clear() {
// @@protoc_insertion_point(message_clear_start:storage_util.Int128)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.high_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.low_) -
      reinterpret_cast<char*>(&_impl_.high_)) + sizeof(_impl_.low_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Int128::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 high = 1 [jstype = JS_STRING];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.high_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 low = 2 [jstype = JS_STRING];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.low_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Int128::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:storage_util.Int128)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 high = 1 [jstype = JS_STRING];
  if (this->_internal_high() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_high(), target);
  }

  // uint64 low = 2 [jstype = JS_STRING];
  if (this->_internal_low() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_low(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:storage_util.Int128)
  return target;
}

size_t Int128::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:storage_util.Int128)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 high = 1 [jstype = JS_STRING];
  if (this->_internal_high() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_high());
  }

  // uint64 low = 2 [jstype = JS_STRING];
  if (this->_internal_low() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_low());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Int128::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Int128::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Int128::GetClassData() const { return &_class_data_; }


void Int128::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Int128*>(&to_msg);
  auto& from = static_cast<const Int128&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:storage_util.Int128)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_high() != 0) {
    _this->_internal_set_high(from._internal_high());
  }
  if (from._internal_low() != 0) {
    _this->_internal_set_low(from._internal_low());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Int128::CopyFrom(const Int128& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:storage_util.Int128)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Int128::IsInitialized() const {
  return true;
}

void Int128::InternalSwap(Int128* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Int128, _impl_.low_)
      + sizeof(Int128::_impl_.low_)
      - PROTOBUF_FIELD_OFFSET(Int128, _impl_.high_)>(
          reinterpret_cast<char*>(&_impl_.high_),
          reinterpret_cast<char*>(&other->_impl_.high_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Int128::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_int128_2eproto_getter, &descriptor_table_int128_2eproto_once,
      file_level_metadata_int128_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace storage_util
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::storage_util::Int128*
Arena::CreateMaybeMessage< ::storage_util::Int128 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::storage_util::Int128 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
