network {
  lines {
    key: "A"
    value {
      hub_ids: "1"
      hub_ids: "2"
      hub_ids: "1"
      next_rotations {
        key: "A_0_2023-01-02"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 13
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 13
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 11
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 11
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 10
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 12
              }
            }
          }
        }
      }
      next_rotations {
        key: "A_0_2023-01-09"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 13
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 13
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 11
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 11
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 10
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 12
              }
            }
          }
        }
      }
      next_rotations {
        key: "A_0_2023-01-16"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 13
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 13
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 11
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 11
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 10
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 12
              }
            }
          }
        }
      }
    }
  }
  lines {
    key: "B"
    value {
      hub_ids: "2"
      hub_ids: "1"
      hub_ids: "2"
      next_rotations {
        key: "B_0_2023-01-02"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 10
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 20
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 20
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 2
                hours: 12
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 2
              }
              last_date {
                year: 2023
                month: 1
                day: 2
              }
            }
          }
        }
      }
      next_rotations {
        key: "B_0_2023-01-09"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 10
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 20
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 20
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 9
                hours: 12
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 9
              }
              last_date {
                year: 2023
                month: 1
                day: 9
              }
            }
          }
        }
      }
      next_rotations {
        key: "B_0_2023-01-16"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 10
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 20
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 20
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 16
                hours: 12
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 16
              }
              last_date {
                year: 2023
                month: 1
                day: 16
              }
            }
          }
        }
      }
      next_rotations {
        key: "B_1_2023-01-03"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 3
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 3
                hours: 10
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 3
                hours: 20
              }
              last_date {
                year: 2023
                month: 1
                day: 3
                hours: 20
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 3
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 3
                hours: 12
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 3
              }
              last_date {
                year: 2023
                month: 1
                day: 3
              }
            }
          }
        }
      }
      next_rotations {
        key: "B_1_2023-01-10"
        value {
          arrival_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 10
                hours: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 10
                hours: 10
              }
            }
          }
          arrival_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 10
                hours: 20
              }
              last_date {
                year: 2023
                month: 1
                day: 10
                hours: 20
              }
            }
          }
          departure_times {
            key: "1"
            value {
              first_date {
                year: 2023
                month: 1
                day: 10
                hours: 12
              }
              last_date {
                year: 2023
                month: 1
                day: 10
                hours: 12
              }
            }
          }
          departure_times {
            key: "2"
            value {
              first_date {
                year: 2023
                month: 1
                day: 10
              }
              last_date {
                year: 2023
                month: 1
                day: 10
              }
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V1_0"
    value {
      current_position_hub: "1"
      capacities {
        value: 800
        dimension: "weight"
      }
      capacities {
        value: 10
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 0.75
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V1_1"
    value {
      current_position_hub: "1"
      capacities {
        value: 800
        dimension: "weight"
      }
      capacities {
        value: 10
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 0.75
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V1_2"
    value {
      current_position_hub: "1"
      capacities {
        value: 800
        dimension: "weight"
      }
      capacities {
        value: 10
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 0.75
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V1_3"
    value {
      current_position_hub: "1"
      capacities {
        value: 800
        dimension: "weight"
      }
      capacities {
        value: 10
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 0.75
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V1_4"
    value {
      current_position_hub: "1"
      capacities {
        value: 800
        dimension: "weight"
      }
      capacities {
        value: 10
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 0.75
            }
          }
        }
      }
    }
  }
  vehicles {
    key: "V2"
    value {
      current_position_hub: "2"
      capacities {
        value: 1600
        dimension: "weight"
      }
      capacities {
        value: 15
        dimension: "parcel"
      }
      cost {
        separable {
          components {
            key: "km"
            value {
              constant: 1
            }
          }
        }
      }
    }
  }
  hubs {
    key: "1"
    value {
      position {
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 2
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 2
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 9
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 9
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 16
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 16
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 3
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 3
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 10
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 10
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 4
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 4
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 11
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 11
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 5
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 5
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 12
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 12
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 6
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 6
          hours: 18
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 13
          hours: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 13
          hours: 18
        }
      }
      cross_docking_capacity {
        capacity_per_hour {
          value: 10
          dimension: "parcel"
        }
      }
      cross_docking_time {
        time_constant {
          seconds: 360
        }
      }
    }
  }
  hubs {
    key: "2"
    value {
      position {
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 2
        }
        last_date {
          year: 2023
          month: 1
          day: 3
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 9
        }
        last_date {
          year: 2023
          month: 1
          day: 10
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 16
        }
        last_date {
          year: 2023
          month: 1
          day: 17
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 3
        }
        last_date {
          year: 2023
          month: 1
          day: 4
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 10
        }
        last_date {
          year: 2023
          month: 1
          day: 11
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 5
        }
        last_date {
          year: 2023
          month: 1
          day: 6
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 12
        }
        last_date {
          year: 2023
          month: 1
          day: 13
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 6
        }
        last_date {
          year: 2023
          month: 1
          day: 7
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 13
        }
        last_date {
          year: 2023
          month: 1
          day: 14
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 7
        }
        last_date {
          year: 2023
          month: 1
          day: 8
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 14
        }
        last_date {
          year: 2023
          month: 1
          day: 15
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 8
        }
        last_date {
          year: 2023
          month: 1
          day: 9
        }
      }
      opening_times {
        first_date {
          year: 2023
          month: 1
          day: 15
        }
        last_date {
          year: 2023
          month: 1
          day: 16
        }
      }
      cross_docking_capacity {
        capacity_per_hour {
          value: 5
          dimension: "parcel"
        }
      }
      cross_docking_time {
        time_constant {
          seconds: 1800
        }
      }
    }
  }
  dimensions {
    value: 1
    dimension: "parcel"
  }
  dimensions {
    value: 1
    dimension: "weight"
  }
  dimensions {
    value: 1
    dimension: "km"
  }
}
parcels {
  key: "P1"
  value {
    source_hub: "1"
    destination_hub: "2"
    arrival_time {
      first_date {
        year: 2023
        month: 1
        day: 8
        hours: 1
        minutes: 2
      }
      last_date {
        year: 2023
        month: 1
        day: 8
        hours: 1
        minutes: 2
      }
    }
    arrival_earliness_tardiness_cost {
      tardiness_cost {
        constant: 25
      }
    }
    size {
      value: 15
      dimension: "weight"
    }
  }
}
parcels {
  key: "P2"
  value {
    source_hub: "2"
    destination_hub: "1"
    arrival_time {
      first_date {
        year: 2023
        month: 1
        day: 8
        hours: 2
        minutes: 1
      }
      last_date {
        year: 2023
        month: 1
        day: 8
        hours: 2
        minutes: 1
      }
    }
    arrival_earliness_tardiness_cost {
      tardiness_cost {
        constant: 30
      }
    }
    size {
      value: 20
      dimension: "weight"
    }
  }
}
