# proto-file: util/operations_research/cloud/lattle/lattle.proto
# proto-message: LogisticsNetwork

name: "two-lines"

dimensions: [
  { value: 1 dimension: "distance" },
  { value: 1 dimension: "time" },
  { value: 1 dimension: "weight" },
  { value: 1 dimension: "pallets" }
]

hubs: [
  { key: "h1" value: {} },
  { key: "h2" value: {} }
]

lines: [
  {
    key: "l1"
    value: {
      next_rotations: [
        {
          key: "l1_lr1"
          value: {
            arrival_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 12 }
                }
              }
            ]
            departure_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 10 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 2.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        },
        {
          key: "l1_lr2"
          value: {
            arrival_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 2 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 2 hours: 12 }
                }
              }
            ]
            departure_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 2 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 2 hours: 10 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 4.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        }
      ]
      hub_ids: ["h1", "h2"]
    }
  },
  {
    key: "l2"
    value: {
      next_rotations: [
        {
          key: "l2_lr1"
          value: {
            arrival_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 12 }
                }
              }
            ]
            departure_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 10 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 3.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        },
        {
          key: "l2_lr2"
          value: {
            arrival_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 12 }
                }
              }
            ]
            departure_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 10 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 5.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        }
      ]
      hub_ids: ["h2", "h1"]
    }
  },
  {
    key: "l3"
    value: {
      next_rotations: [
        {
          key: "l3_lr1"
          value: {
            arrival_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 12 }
                }
              },
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 16 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 16 }
                }
              }
            ]
            departure_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 10 }
                }
              },
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 14 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 14 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 10.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        },
        {
          key: "l3_lr2"
          value: {
            arrival_times: [
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 12 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 12 }
                }
              },
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 16 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 16 }
                }
              }
            ]
            departure_times: [
              {
                key: "h2"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 10 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 10 }
                }
              },
              {
                key: "h1"
                value: {
                  first_date: { year: 2023 month: 1 day: 1 hours: 14 }
                  last_date: { year: 2023 month: 1 day: 1 hours: 14 }
                }
              }
            ]
            fixed_price: { separable: { constant_price: 25.0 } }
            maximum_number_vehicles: {
              start_value: 1
              end_value: 1
            }
          }
        }
      ]
      hub_ids: ["h2", "h1", "h2"]
    }
  }
]

vehicles: [
  {
    key: "v1"
    value: {
      capacities: [
        { value: 2 dimension: "pallets" },
        { value: 4 dimension: "weight" }
      ]
    }
  },
  {
    key: "v2"
    value: {
      capacities: [
        { value: 3 dimension: "pallets" },
        { value: 5 dimension: "weight" }
      ]
    }
  }
]

distance_matrix: [
  {
    source_hub: "h1"
    destination_hub: "h2"
    weights: [
      { value: 4 dimension: "distance" },
      { value: 9 dimension: "time" }
    ]
  },
  {
    source_hub: "h2"
    destination_hub: "h1"
    weights: [
      { value: 5 dimension: "distance" },
      { value: 6 dimension: "time" }
    ]
  }
]
