# proto-file: util/operations_research/cloud/lattle/lattle.proto
# proto-message: LogisticsNetworkState

network: "two-lines"

routed_parcels: [
  {
    parcel: "p1"
    source_hub: "h1"
    destination_hub: "h2"
    size: [
      {
        dimension: "pallets"
        value: 1
      },
      {
        dimension: "weight"
        value: 1
      }
    ]
  },
  {
    parcel: "p2"
    source_hub: "h2"
    destination_hub: "h1"
    size: [
      {
        dimension: "pallets"
        value: 2
      },
      {
        dimension: "weight"
        value: 3
      }
    ]
  }
]

parcel_routes: [
  {
    parcel: "p1"
    path_segments: [
      {
        arrival_time: {
          year: 2023
          month: 1
          day: 1
          hours: 14
          minutes: 0
          seconds: 0
        }
        departure_time: {
          year: 2023
          month: 1
          day: 1
          hours: 12
          minutes: 0
          seconds: 0
        }
        path_segment: {
          source_hub: "h1"
          destination_hub: "h2"
          line: "l1"
          line_rotation: "l1_lr1"
          vehicle: "v1"
        }
      }
    ]
  },
  {
    parcel: "p2"
    path_segments: [
      {
        path_segment: {
          source_hub: "h2"
          destination_hub: "h1"
          line: "l2"
          line_rotation: "l2_lr1"
          vehicle: "v2"
        }
      }
    ]
  }
]

used_capacity_in_vehicle: [
  {
    line: "l1"
    line_rotation: "l1_lr1"
    vehicle: "v1"
    used_capacity: [
      {
        dimension: "pallets"
        value: 2
      },
      {
        dimension: "weight"
        value: 4
      }
    ]
    source_hub: "h1"
    destination_hub: "h2"
  },
  {
    line: "l2"
    line_rotation: "l2_lr1"
    vehicle: "v2"
    used_capacity: [
      {
        dimension: "pallets"
        value: 0
      },
      {
        dimension: "weight"
        value: 4
      }
    ]
    source_hub: "h2"
    destination_hub: "h1"
  }
]
